version: "2.27" 
# version de docker compose obtenue grace a la commande 
# docker compose version

services:
  maria_db:
    build: ./requirements/mariadb
    container_name: mariadb_container
    env_file:
      - .env
    # ports:
    #   - "3306:3306"
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_container
    depends_on:
      - mariadb
    env_file:
      - .env
    # ports:
    #   - 9000-9000
    restart: always
    volumes:
      - wordpress:wordpress

  nginx:
    build: ./requirements/nginx
    container_name: nginx_container
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      443:443
    restart: always
 
volumes:
  mariadb_data: