services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - ~./amennad/data/mariadb:/var/lib/mysql/$DB_NAME
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - ~./amennad/data/wordpress:/var/www/wordpress
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - ~./amennad/data/wordpress:/var/www/wordpress
    restart: always
    networks:
      - inception

volumes:
  mariadb:
  wordpress:

networks:
  inception:
