services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql/$DB_NAME
    network:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    network:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    network:
      - inception

volume:
  mariadb:
  wordpress:

network:
  inception:
